# Generated by Django 4.2.20 on 2025-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'longitude', 'latitude')},
        ),
    ]
