# Generated by Django 4.2.20 on 2025-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_places_options_alter_placeimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='place_id_slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Идентификатор для URL (слаг)'),
        ),
    ]
