# Generated by Django 4.2.20 on 2025-05-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_places_place_id_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='place_id_slug',
        ),
    ]
